name: Compile LaTeX to PDF
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write  # Required for pushing changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Compile PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          
      - name: Save PDF in docs folder
        run: |
          mkdir -p docs
          cp main.pdf docs/
          
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit PDF to docs for GitHub Pages
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/main.pdf
          git commit -m "Auto-update PDF [skip ci]"
          git push
