name: Build PDF

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex  # Replace with your file
          
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: main.pdf
      - name: Move PDF to docs folder
        run: |
          mkdir -p docs
          cp main.pdf docs/
      - name: Commit PDF to repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/main.pdf
          git commit -m "Update compiled PDF"
          git push
